logging:
    file:
        path: D:/springboot-log/log
    level:
        com:
            wry:
                dao: DEBUG
        root: INFO
    pattern:
        console: ${CONSOLE_LOG_PATTERN:%clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%15.15t]){faint}
            %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
mybatis:
    mapper-locations: com/wry/dao/*.xml

server:
    port: 8080

spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/k15-db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root

    servlet:
        multipart:
            max-file-size: 30MB
            max-request-size: 60MB
